server:
  port: ${PORT:5000}

spring:
  rabbitmq:
    host: ${RABBIT_URL:localhost}
  application:
    name: carRental
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: false
    hibernate:
      ddl-auto: update

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false

token:
  privateKey: ${PRIVATE_KEY:688787d8ff144c502c7f5cffaafe2cc588d86079f9de88304c26b0cb99ce91c6}
  issuer: ${ISSUER:webservice1.carRental}
  expirationTime: ${EXPIRATION_TIME:60}

webservice2:
  url: ${WEBSERVICE2_URL:http://localhost:4000/ws/currency-converter}

soap:
  admin:
    name: ${SOAP_ADMIN_NAME:admin}
    secret: ${SOAP_ADMIN_SECRET:pwd123}
