server:
  port: ${PORT:5003}

spring:
  rabbitmq:
    host: ${RABBIT_URL:localhost}
  application:
    name: car-microservice
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: cardb
