server:
  port: ${PORT:5003}

spring:
  rabbitmq:
    host: ${RABBIT_URL:localhost}
  application:
    name: car-microservice
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://localhost:27017/}
      database: cardb
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

webservice2:
  url: ${WEBSERVICE2_URL:http://localhost:4000/ws/currency-converter}

soap:
  admin:
    name: ${SOAP_ADMIN_NAME:admin}
    secret: ${SOAP_ADMIN_SECRET:pwd123}
