server:
  port: ${PORT:5001}

spring:
  rabbitmq:
    host: ${RABBIT_URL:localhost}
  application:
    name: user-microservice
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGODB_URL:mongodb://root:example@localhost:27017/userdb}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
