server:
  port: ${PORT:5001}

spring:
  rabbitmq:
    host: ${RABBIT_URL:localhost}
  application:
    name: user-microservice
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://localhost:27017/}
      database: userdb
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
