# Use root/example as user/password credentials
version: '3.1'
services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=userdb
      - MONGO_INITDB_DATABASE=cardb
      - MONGO_INITDB_DATABASE=rentaldb
    ports:
    - 27017:27017
